// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnW0fGcwjyikoMSUbSkGhvNcC988tk4Nc',
    appId: '1:521979078754:web:b7be20a3ba01ae26e5093b',
    messagingSenderId: '521979078754',
    projectId: 'attender-e5f34',
    authDomain: 'attender-e5f34.firebaseapp.com',
    storageBucket: 'attender-e5f34.appspot.com',
    measurementId: 'G-KT53MG72FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_b6G3GKhQkwtJ8xK47EumRPPOZwgyek',
    appId: '1:521979078754:android:bcbbe0aa35c0bed4e5093b',
    messagingSenderId: '521979078754',
    projectId: 'attender-e5f34',
    storageBucket: 'attender-e5f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRSgQYEHekXGXAtmj3T4WvwXy-ss-z3is',
    appId: '1:521979078754:ios:52a89cb3de8d6932e5093b',
    messagingSenderId: '521979078754',
    projectId: 'attender-e5f34',
    storageBucket: 'attender-e5f34.appspot.com',
    iosClientId: '521979078754-5vggl3qdif7mlua4rip64vjoja0d85s7.apps.googleusercontent.com',
    iosBundleId: 'com.Priyabrat.attender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRSgQYEHekXGXAtmj3T4WvwXy-ss-z3is',
    appId: '1:521979078754:ios:75aafe2b4cb7e760e5093b',
    messagingSenderId: '521979078754',
    projectId: 'attender-e5f34',
    storageBucket: 'attender-e5f34.appspot.com',
    iosClientId: '521979078754-co3fsfhqq1huev9p8ve7oonjsmugkj09.apps.googleusercontent.com',
    iosBundleId: 'com.example.attender',
  );
}
